import { CategoryMetadata, ToolCategory } from "./tool-types";

export const CATEGORIES: Record<ToolCategory, CategoryMetadata> = {
  pdf: {
    id: "pdf",
    name: "PDF Utilities",
    description: "Compress, merge, split, encrypt, rotate, and manipulate PDF documents with 100% in-browser privacy.",
    iconName: "FileText",
    badgeColor: "rose",
    gradient: "from-rose-500/20 to-red-500/20 border-rose-500/30",
    popularKeywords: ["compress pdf", "merge pdf", "pdf password", "split pdf", "rotate pdf"],
  },
  image: {
    id: "image",
    name: "Image Processing",
    description: "Resize, compress, crop, convert formats, and optimize images directly on your device.",
    iconName: "Image",
    badgeColor: "cyan",
    gradient: "from-cyan-500/20 to-blue-500/20 border-cyan-500/30",
    popularKeywords: ["compress image", "image resizer", "jpg to png", "crop image", "webp converter"],
  },
  text: {
    id: "text",
    name: "Text & Writing",
    description: "Word counters, case converters, line sorters, text formatters, and typography utilities.",
    iconName: "Type",
    badgeColor: "emerald",
    gradient: "from-emerald-500/20 to-teal-500/20 border-emerald-500/30",
    popularKeywords: ["word counter", "case converter", "lorem ipsum", "text cleaner", "line sorter"],
  },
  developer: {
    id: "developer",
    name: "Developer Utilities",
    description: "Formatters, minifiers, encoders, decoders, regex testers, and data conversion tools for engineers.",
    iconName: "Code2",
    badgeColor: "amber",
    gradient: "from-amber-500/20 to-orange-500/20 border-amber-500/30",
    popularKeywords: ["json formatter", "jwt decoder", "sql formatter", "base64", "uuid generator"],
  },
  calculators: {
    id: "calculators",
    name: "Calculators & Math",
    description: "Financial, geometric, mathematical, date, health, and everyday calculations with instant results.",
    iconName: "Calculator",
    badgeColor: "indigo",
    gradient: "from-indigo-500/20 to-violet-500/20 border-indigo-500/30",
    popularKeywords: ["emi calculator", "percentage calculator", "age calculator", "sip calculator", "bmi calculator"],
  },
  india: {
    id: "india",
    name: "India Utilities",
    description: "Government exam photo resizers, GST tax calculators, income tax regime tools, and Indian financial utilities.",
    iconName: "Landmark",
    badgeColor: "orange",
    gradient: "from-orange-500/20 to-amber-500/20 border-orange-500/30",
    popularKeywords: ["passport photo resize", "gst calculator", "signature 20kb", "old vs new tax", "upsc photo"],
  },
  tamil: {
    id: "tamil",
    name: "Tamil Utilities",
    description: "Tamil OCR, Tanglish transliteration, BAMINI to Unicode converter, and Tamil text processing tools.",
    iconName: "Languages",
    badgeColor: "purple",
    gradient: "from-purple-500/20 to-fuchsia-500/20 border-purple-500/30",
    popularKeywords: ["tamil ocr", "tanglish to tamil", "bamini to unicode", "tamil word counter"],
  },
  data: {
    id: "data",
    name: "Data & Format Tools",
    description: "Convert, transform, validate, and extract datasets across JSON, CSV, XML, YAML, and SQL formats.",
    iconName: "Database",
    badgeColor: "blue",
    gradient: "from-blue-500/20 to-sky-500/20 border-blue-500/30",
    popularKeywords: ["json to csv", "csv to json", "csv to markdown", "json to typescript", "yaml to json"],
  },
  seo: {
    id: "seo",
    name: "SEO & Search Tools",
    description: "Generate meta tags, robots.txt, XML sitemaps, slugify URLs, and analyze search keyword density.",
    iconName: "Search",
    badgeColor: "teal",
    gradient: "from-teal-500/20 to-emerald-500/20 border-teal-500/30",
    popularKeywords: ["meta tag generator", "robots.txt", "sitemap generator", "url slug", "keyword density"],
  },
  webmaster: {
    id: "webmaster",
    name: "Webmaster & Network",
    description: "CIDR subnet calculators, HTTP status lookups, DNS record builders, and server redirect generators.",
    iconName: "Globe",
    badgeColor: "sky",
    gradient: "from-sky-500/20 to-blue-500/20 border-sky-500/30",
    popularKeywords: ["cidr calculator", "http status codes", "htaccess redirect", "user agent parser"],
  },
  finance: {
    id: "finance",
    name: "Finance & Business",
    description: "Profit margin, ROI, break-even, sales tax, currency, and invoice calculation utilities.",
    iconName: "DollarSign",
    badgeColor: "emerald",
    gradient: "from-emerald-500/20 to-green-500/20 border-emerald-500/30",
    popularKeywords: ["profit margin", "roi calculator", "break even calculator", "hourly to salary"],
  },
  education: {
    id: "education",
    name: "Education & Students",
    description: "GPA / CGPA calculators, citation builders (APA/MLA), grade conversions, and scientific tools.",
    iconName: "GraduationCap",
    badgeColor: "yellow",
    gradient: "from-yellow-500/20 to-amber-500/20 border-yellow-500/30",
    popularKeywords: ["gpa calculator", "percentage to cgpa", "apa citation generator", "scientific notation"],
  },
  accessibility: {
    id: "accessibility",
    name: "Accessibility (A11y)",
    description: "WCAG color contrast checkers, alt text builders, and dyslexic-friendly text previewers.",
    iconName: "Eye",
    badgeColor: "lime",
    gradient: "from-lime-500/20 to-green-500/20 border-lime-500/30",
    popularKeywords: ["color contrast checker", "wcag contrast", "image alt text", "accessible palette"],
  },
  privacy: {
    id: "privacy",
    name: "Privacy & Security",
    description: "Password generators, hash verifiers, string obfuscators, and client-side entropy testers.",
    iconName: "ShieldCheck",
    badgeColor: "cyan",
    gradient: "from-cyan-500/20 to-teal-500/20 border-cyan-500/30",
    popularKeywords: ["password generator", "password strength", "sha256 verifier", "token generator"],
  },
  qr: {
    id: "qr",
    name: "QR & Barcodes",
    description: "Generate and scan custom QR codes for URLs, WiFi, vCards, and industrial barcodes.",
    iconName: "QrCode",
    badgeColor: "violet",
    gradient: "from-violet-500/20 to-purple-500/20 border-violet-500/30",
    popularKeywords: ["qr code generator", "wifi qr code", "barcode generator", "vcard qr"],
  },
  file: {
    id: "file",
    name: "File & Checksum Tools",
    description: "Compute file hashes (SHA-256), sanitize filenames, compare file sizes, and slice text documents.",
    iconName: "FileArchive",
    badgeColor: "slate",
    gradient: "from-slate-500/20 to-gray-500/20 border-slate-500/30",
    popularKeywords: ["file checksum", "sha256 hash", "sanitize filename", "file size comparator"],
  },
  ocr: {
    id: "ocr",
    name: "OCR & Vision",
    description: "Extract editable text from images, scanned documents, screenshots, and business cards.",
    iconName: "ScanText",
    badgeColor: "indigo",
    gradient: "from-indigo-500/20 to-blue-500/20 border-indigo-500/30",
    popularKeywords: ["ocr image to text", "screenshot ocr", "extract text from image"],
  },
  business: {
    id: "business",
    name: "Business Tools",
    description: "NDAs, purchase order summaries, pricing tier matrices, and business document helpers.",
    iconName: "Briefcase",
    badgeColor: "blue",
    gradient: "from-blue-500/20 to-indigo-500/20 border-blue-500/30",
    popularKeywords: ["nda generator", "pricing table generator", "business invoice"],
  },
  productivity: {
    id: "productivity",
    name: "Productivity Tools",
    description: "Pomodoro focus timers, time zone difference planners, habit streak math, and daily organizers.",
    iconName: "Clock",
    badgeColor: "amber",
    gradient: "from-amber-500/20 to-yellow-500/20 border-amber-500/30",
    popularKeywords: ["pomodoro timer", "time zone planner", "meeting cost calculator"],
  },
  ai: {
    id: "ai",
    name: "AI & Prompts",
    description: "AI prompt formatters, token count estimators, few-shot example builders, and prompt cleaners.",
    iconName: "Sparkles",
    badgeColor: "fuchsia",
    gradient: "from-fuchsia-500/20 to-pink-500/20 border-fuchsia-500/30",
    popularKeywords: ["prompt formatter", "token counter", "system prompt builder"],
  },
  audio: {
    id: "audio",
    name: "Audio Utilities",
    description: "In-browser waveform analyzers, BPM beat counters, tone generators, and audio converters.",
    iconName: "Music",
    badgeColor: "rose",
    gradient: "from-rose-500/20 to-pink-500/20 border-rose-500/30",
    popularKeywords: ["bpm counter", "audio waveform", "tone generator", "audio base64"],
  },
  video: {
    id: "video",
    name: "Video Utilities",
    description: "Video frame extractors, aspect ratio calculators, resolution scalers, and GIF makers.",
    iconName: "Video",
    badgeColor: "red",
    gradient: "from-red-500/20 to-rose-500/20 border-red-500/30",
    popularKeywords: ["video to gif", "aspect ratio calculator", "video frame extractor"],
  },
  social: {
    id: "social",
    name: "Social Media",
    description: "Format Instagram captions, clean YouTube tags, check character limits, and generate hashtags.",
    iconName: "Share2",
    badgeColor: "pink",
    gradient: "from-pink-500/20 to-rose-500/20 border-pink-500/30",
    popularKeywords: ["instagram line break", "youtube tags", "tweet character counter", "hashtag cleaner"],
  },
  marketing: {
    id: "marketing",
    name: "Marketing & Growth",
    description: "UTM campaign builders, SERP previewers, headline capitalizers, and email subject analyzers.",
    iconName: "TrendingUp",
    badgeColor: "emerald",
    gradient: "from-emerald-500/20 to-teal-500/20 border-emerald-500/30",
    popularKeywords: ["utm builder", "serp preview", "email subject analyzer", "headline capitalizer"],
  },
  design: {
    id: "design",
    name: "Design & CSS",
    description: "Generate CSS box shadows, gradients, glassmorphism filters, grid layouts, and color palettes.",
    iconName: "Palette",
    badgeColor: "violet",
    gradient: "from-violet-500/20 to-indigo-500/20 border-violet-500/30",
    popularKeywords: ["css box shadow", "css gradient", "glassmorphism generator", "flexbox playground"],
  },
};

export function getAllCategories(): CategoryMetadata[] {
  return Object.values(CATEGORIES);
}

export function getCategoryById(id: string): CategoryMetadata | undefined {
  return CATEGORIES[id as ToolCategory];
}
